use_frameworks!

target 'ArrayPlusTuple_Example' do
  pod 'ArrayPlusTuple', :path => '../'

  target 'ArrayPlusTuple_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
