use_frameworks!

target 'ArrayPlusTuple_Example' do
  pod 'ArrayPlusTuple', :path => '../'

  target 'ArrayPlusTuple_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'QuickGWT', '~> 1.0.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
